/**
 * Backfill issue covers by rendering the first page of each archive PDF.
 *
 *   pnpm run backfill:pdf-covers -- --dry-run
 *   pnpm run backfill:pdf-covers -- --limit 5
 *   pnpm run backfill:pdf-covers -- --force
 *   pnpm run backfill:pdf-covers -- --date 2026-05-01
 *   pnpm run backfill:pdf-covers -- --force --cleanup          (report orphans)
 *   pnpm run backfill:pdf-covers -- --force --cleanup-delete   (and remove them)
 *
 * Needs SUPABASE_SERVICE_ROLE_KEY in .env: this writes to storage and to
 * public.pages, neither of which anon may do.
 *
 * WHY THIS EXISTS
 *   Covers are normally generated in-request by the archives:cover hook during
 *   a Notion sync, and that remains the intended workflow. But two rounds of
 *   breakage left the archive in a bad state:
 *
 *     1. Covers generated before Sep 2026 were rasterised by pdfjs *without*
 *        its canvas polyfills, onto a transparent canvas. A PDF page carries
 *        no background of its own, so anything the page did not explicitly
 *        paint stayed alpha-0 and text using knockout/transparency groups
 *        composited against nothing. Those covers look wrong and need
 *        replacing -- use --force.
 *     2. Covers after that failed outright, because pdf-to-img/pdfjs reaches
 *        for @napi-rs/canvas at runtime and it was never a dependency. Those
 *        pages have no cover at all and are picked up by default.
 *
 *   Re-syncing every archive page through Notion just to regenerate an image
 *   is slow and churns last_synced_at for no reason, hence a direct script.
 *
 * It deliberately calls the very same generateThumbnailBuffer() the hook uses,
 * so a page fixed here is byte-identical to one generated by a future sync.
 */

// Relative, not '$lib/...': `$lib` is a Vite alias and this runs under tsx,
// which does not know about SvelteKit's aliases.
import { symbiont } from '../src/lib/symbiont.js';
import { generateThumbnailBuffer } from '../src/lib/sync/hooks/tech.js';
import { uploadBufferToSupabase, cleanupUnusedMedia } from 'symbiont-cms/server';
import { createHash } from 'node:crypto';
import sharp from 'sharp';
import 'dotenv/config';

const ARCHIVE_ALIAS = 'tech-archives';
const PAGE_SIZE = 500;

const args = process.argv.slice(2);
const hasFlag = (name: string) => args.includes(`--${name}`);
const flagValue = (name: string) => {
  const index = args.indexOf(`--${name}`);
  return index === -1 ? undefined : args[index + 1];
};

const force = hasFlag('force');
const dryRun = hasFlag('dry-run');
const onlyDate = flagValue('date');
const limit = Number(flagValue('limit') ?? Number.POSITIVE_INFINITY);

/**
 * Sweep orphaned media after the backfill.
 *
 * Re-rendering does not overwrite the old cover: the object name is
 * sha256(pdfUrl) and the archive's PDF URLs just changed en masse (padding,
 * encoding, and five now pointing at Supabase), so almost every cover lands
 * under a NEW name and the previous one is left behind. A --force run over the
 * whole archive strands on the order of two thousand PNGs.
 *
 * --cleanup only ever reports. --cleanup-delete is required to remove anything,
 * because this deletes from the bucket holding the paper's real media and
 * cleanupUnusedMedia's notion of "referenced" is narrower than this app's --
 * see checkMetaReferences below.
 */
const cleanup = hasFlag('cleanup') || hasFlag('cleanup-delete');
const cleanupDelete = hasFlag('cleanup-delete');

const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!serviceRoleKey) {
  console.error('SUPABASE_SERVICE_ROLE_KEY is not set (expected in .env).');
  process.exit(1);
}

const supabase = symbiont.getSSRClient(undefined, serviceRoleKey);

type ArchiveRow = {
  page_id: string;
  slug: string | null;
  title: string | null;
  cover: string | null;
  meta: Record<string, unknown> | null;
};

/** The archive stores its PDF link in meta.resolver_url. */
function getPdfUrl(row: ArchiveRow): string | null {
  const url = row.meta?.resolver_url;
  return typeof url === 'string' && url.toLowerCase().endsWith('.pdf') ? url : null;
}

async function fetchArchiveRows(): Promise<ArchiveRow[]> {
  const rows: ArchiveRow[] = [];

  for (let offset = 0; ; offset += PAGE_SIZE) {
    const { data, error } = await supabase
      .from('pages')
      .select('page_id, slug, title, cover, meta')
      .eq('datasource_alias', ARCHIVE_ALIAS)
      .order('slug', { ascending: false })
      .range(offset, offset + PAGE_SIZE - 1);

    if (error) throw new Error(`Failed to list archive pages: ${error.message}`);
    if (!data || data.length === 0) break;

    rows.push(...(data as ArchiveRow[]));
    if (data.length < PAGE_SIZE) break;
  }

  return rows;
}

const MEDIA_PATH_RE = /\/media\/([^?#\s"')]+)/g;

/**
 * Media paths referenced from places cleanupUnusedMedia does not look.
 *
 * The library scans `pages.content` and `pages.cover` only. This app also
 * resolves covers out of `meta.cover` -- see getStoredIssueCover() in
 * issues.ts, which falls back to it -- and `summary` can carry markdown images.
 * Anything referenced there looks unreferenced to the library and would be
 * deleted. This collects those paths so the sweep below can refuse.
 *
 * The right long-term fix is for cleanupUnusedMedia to take the columns to
 * scan, or for this app to stop storing covers in meta. Until then, this guard
 * is what stands between a --force run and deleting live images.
 */
async function collectMetaReferences(): Promise<Set<string>> {
  const referenced = new Set<string>();
  const PAGE_SIZE = 1000;

  for (let offset = 0; ; offset += PAGE_SIZE) {
    const { data, error } = await supabase
      .from('pages')
      .select('meta, summary')
      .range(offset, offset + PAGE_SIZE - 1);

    if (error) throw new Error(`Failed to scan pages for media references: ${error.message}`);
    if (!data || data.length === 0) break;

    for (const row of data as Array<{ meta: unknown; summary: string | null }>) {
      for (const text of [row.meta ? JSON.stringify(row.meta) : '', row.summary ?? '']) {
        if (!text) continue;
        MEDIA_PATH_RE.lastIndex = 0;
        let match: RegExpExecArray | null;
        while ((match = MEDIA_PATH_RE.exec(text)) !== null) referenced.add(match[1]!);
      }
    }

    if (data.length < PAGE_SIZE) break;
  }

  return referenced;
}

async function runCleanup() {
  console.log('\n' + '='.repeat(64));
  console.log('MEDIA CLEANUP');
  console.log('='.repeat(64));

  // Always dry-run first, whatever the flags say: the result is what the guard
  // below inspects, and it is also what gets printed for review.
  const preview = await cleanupUnusedMedia(supabase, { dryRun: true });
  console.log(
    `${preview.totalInBucket} objects in bucket, ${preview.referencedCount} referenced, ` +
      `${preview.deleted} unreferenced`,
  );
  console.log('(the issues/ prefix is excluded by the library, so issue PDFs are never touched)');

  if (preview.deleted === 0) {
    console.log('Nothing to sweep.');
    return;
  }

  const metaReferenced = await collectMetaReferences();
  const wouldDeleteLive = preview.deletedPaths.filter((path) => metaReferenced.has(path));

  if (wouldDeleteLive.length > 0) {
    console.error(`\n!! ABORTING: ${wouldDeleteLive.length} of these are still referenced from meta/summary,`);
    console.error('   which cleanupUnusedMedia does not scan. Deleting them would break live images:');
    for (const path of wouldDeleteLive.slice(0, 20)) console.error(`     ${path}`);
    if (wouldDeleteLive.length > 20) console.error(`     ... and ${wouldDeleteLive.length - 20} more`);
    console.error('\n   Move those references into pages.cover, or narrow the sweep, before deleting.');
    return;
  }

  console.log(`\nNone of the ${preview.deleted} are referenced from meta or summary. Sample:`);
  for (const path of preview.deletedPaths.slice(0, 15)) console.log(`   ${path}`);
  if (preview.deletedPaths.length > 15) console.log(`   ... and ${preview.deletedPaths.length - 15} more`);

  if (!cleanupDelete) {
    console.log('\nDry run. Re-run with --cleanup-delete to actually remove them.');
    return;
  }

  const result = await cleanupUnusedMedia(supabase, { dryRun: false });
  console.log(`\nDeleted ${result.deleted} objects.`);
  console.log('Note: image_metadata rows for the deleted paths are now stale; they are harmless');
  console.log('(the cover join simply misses) but can be pruned if you care.');
}

async function main() {
  const rows = await fetchArchiveRows();
  console.log(`${rows.length} pages in "${ARCHIVE_ALIAS}"`);

  const candidates = rows.filter((row) => {
    if (!getPdfUrl(row)) return false;
    if (onlyDate && !(row.slug ?? '').includes(onlyDate)) return false;
    // Without --force, only pages that have no cover at all. With it, every
    // page is re-rendered, which is how the transparent-background covers get
    // replaced.
    return force || !row.cover;
  });

  const selected = candidates.slice(0, Number.isFinite(limit) ? limit : undefined);
  console.log(
    `${candidates.length} need covers (${force ? 'force: re-rendering existing' : 'missing only'})` +
      (selected.length < candidates.length ? `, processing ${selected.length} due to --limit` : ''),
  );

  if (dryRun) {
    for (const row of selected) {
      console.log(`  would render ${row.slug ?? row.page_id} <- ${getPdfUrl(row)}`);
    }
    console.log('\nDry run: nothing written.');
    if (cleanup) await runCleanup();
    return;
  }

  let ok = 0;
  let failed = 0;

  // Sequential on purpose. Rasterising a broadsheet page holds a large bitmap
  // in WASM memory; doing several at once is a good way to get OOM-killed.
  for (const [index, row] of selected.entries()) {
    const pdfUrl = getPdfUrl(row)!;
    const label = row.slug ?? row.page_id;
    const position = `[${index + 1}/${selected.length}]`;

    try {
      const buffer = await generateThumbnailBuffer(pdfUrl);
      const { width, height } = await sharp(buffer).metadata();

      // Same derivation as the hook, so re-running replaces the object in
      // place rather than orphaning the old one (upload uses upsert: true).
      const hash = createHash('sha256').update(pdfUrl).digest('hex').substring(0, 12);
      const filename = `${hash}_cover.png`;

      const { newUrl } = await uploadBufferToSupabase(buffer, {
        supabase,
        filename,
        contentType: 'image/png',
      });

      const { error: updateError } = await supabase.from('pages').update({ cover: newUrl }).eq('page_id', row.page_id);

      if (updateError) throw new Error(`pages.cover update failed: ${updateError.message}`);

      // uploadBufferToSupabase does not record dimensions (only the image
      // upload path does), and re-rendering changes them. Left stale, the
      // image_metadata join hands the front end the old cover's aspect ratio
      // and reintroduces layout shift.
      if (width && height) {
        const { error: metaError } = await supabase
          .from('image_metadata')
          .upsert(
            { bucket_id: 'media', object_path: filename, width, height },
            { onConflict: 'bucket_id,object_path' },
          );
        if (metaError) console.warn(`    ! image_metadata upsert failed: ${metaError.message}`);
      }

      console.log(`  ✓ ${position} ${label} → ${width}×${height}`);
      ok++;
    } catch (error) {
      console.warn(`  ✗ ${position} ${label}: ${error instanceof Error ? error.message : String(error)}`);
      failed++;
    }
  }

  console.log(`\nDone. ${ok} succeeded, ${failed} failed.`);

  // After the renders, so the newly-written covers count as referenced. Skipped
  // when renders failed: a failed render leaves the old cover in place and
  // still referenced, but a partial run is the wrong moment to be deleting.
  if (cleanup) {
    if (failed > 0) {
      console.log(`\nSkipping cleanup: ${failed} renders failed. Re-run once those are resolved.`);
    } else {
      await runCleanup();
    }
  }

  if (ok > 0 && force) {
    console.log(
      'Note: replaced objects keep their URL and were uploaded with a one-year\n' +
        'cacheControl, so already-cached copies may persist in browsers for a while.',
    );
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
